# C:\Users\pedro\Desktop\projetos\Breno\gerador-conteudo\.streamlit\secrets.toml
APP_PASSWORD = "12345678"
GITHUB_TOKEN = "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"
GIST_ID = "9df67c4a302f94b3a819039f417901e7"
GIST_FILENAME = "labels.csv"

